name: Format Python code

on:
  push:
    branches:
      - main  # Change this to your repository's default branch name

jobs:
  format:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  #  the desired Python version

      - name: Install dependencies
        run: python -m pip install --upgrade pip
        # Add any other dependencies your code may require

      - name: Format code
        run: pip install black && black .
